// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ctesp2425_final_gAf.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250207022539_migrationDB")]
    partial class migrationDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ctesp2425_final_gAf.Models.Reservation", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime?>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("CustomerName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("NumberOfPeople")
                    .HasColumnType("int");

                b.Property<DateOnly>("ReservationDate")
                    .HasColumnType("date");

                b.Property<TimeOnly>("ReservationTime")
                    .HasColumnType("time");

                b.Property<int>("StatusReservation")
                    .HasColumnType("int");

                b.Property<int>("TableNumber")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("dsosReservation", (string)null);
            });
#pragma warning restore 612, 618
        }
    }
}